// Code generated by protoc-gen-go.
// source: endpoints.proto
// DO NOT EDIT!

/*
Package endpoints is a generated protocol buffer package.

It is generated from these files:
	endpoints.proto

It has these top-level messages:
	Endpoint
	Period
	EndpointsScanner
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Period_PeriodType int32

const (
	Period_SECONDS Period_PeriodType = 1
	Period_MINUTES Period_PeriodType = 2
	Period_HOURS   Period_PeriodType = 3
	Period_DAYS    Period_PeriodType = 4
)

var Period_PeriodType_name = map[int32]string{
	1: "SECONDS",
	2: "MINUTES",
	3: "HOURS",
	4: "DAYS",
}
var Period_PeriodType_value = map[string]int32{
	"SECONDS": 1,
	"MINUTES": 2,
	"HOURS":   3,
	"DAYS":    4,
}

func (x Period_PeriodType) Enum() *Period_PeriodType {
	p := new(Period_PeriodType)
	*p = x
	return p
}
func (x Period_PeriodType) String() string {
	return proto.EnumName(Period_PeriodType_name, int32(x))
}
func (x *Period_PeriodType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Period_PeriodType_value, data, "Period_PeriodType")
	if err != nil {
		return err
	}
	*x = Period_PeriodType(value)
	return nil
}
func (Period_PeriodType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Endpoint struct {
	Host             *string `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Port             *uint32 `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *Endpoint) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type Period struct {
	Period           *uint64            `protobuf:"varint,1,req,name=period" json:"period,omitempty"`
	PeriodType       *Period_PeriodType `protobuf:"varint,2,req,name=period_type,enum=Period_PeriodType" json:"period_type,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Period) Reset()                    { *m = Period{} }
func (m *Period) String() string            { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()               {}
func (*Period) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Period) GetPeriod() uint64 {
	if m != nil && m.Period != nil {
		return *m.Period
	}
	return 0
}

func (m *Period) GetPeriodType() Period_PeriodType {
	if m != nil && m.PeriodType != nil {
		return *m.PeriodType
	}
	return Period_SECONDS
}

type EndpointsScanner struct {
	Period           *Period     `protobuf:"bytes,1,req,name=period" json:"period,omitempty"`
	Endpoints        []*Endpoint `protobuf:"bytes,2,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *EndpointsScanner) Reset()                    { *m = EndpointsScanner{} }
func (m *EndpointsScanner) String() string            { return proto.CompactTextString(m) }
func (*EndpointsScanner) ProtoMessage()               {}
func (*EndpointsScanner) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EndpointsScanner) GetPeriod() *Period {
	if m != nil {
		return m.Period
	}
	return nil
}

func (m *EndpointsScanner) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "Endpoint")
	proto.RegisterType((*Period)(nil), "Period")
	proto.RegisterType((*EndpointsScanner)(nil), "EndpointsScanner")
	proto.RegisterEnum("Period_PeriodType", Period_PeriodType_name, Period_PeriodType_value)
}

func init() { proto.RegisterFile("endpoints.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcd, 0x4b, 0x29,
	0xc8, 0xcf, 0xcc, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe3, 0xe2, 0x70,
	0x85, 0x0a, 0x09, 0xf1, 0x70, 0xb1, 0x64, 0xe4, 0x17, 0x97, 0x48, 0x30, 0x2a, 0x30, 0x69, 0x70,
	0x82, 0x78, 0x05, 0xf9, 0x45, 0x25, 0x12, 0x4c, 0x40, 0x1e, 0xaf, 0x52, 0x1d, 0x17, 0x5b, 0x40,
	0x6a, 0x51, 0x66, 0x7e, 0x8a, 0x10, 0x1f, 0x17, 0x5b, 0x01, 0x98, 0x05, 0x56, 0xc7, 0x22, 0xa4,
	0xce, 0xc5, 0x0d, 0xe1, 0xc7, 0x97, 0x54, 0x16, 0xa4, 0x82, 0x95, 0xf3, 0x19, 0x09, 0xe9, 0x41,
	0x54, 0x43, 0xa9, 0x10, 0xa0, 0x8c, 0x92, 0x35, 0x17, 0x17, 0x82, 0x27, 0xc4, 0xcd, 0xc5, 0x1e,
	0xec, 0xea, 0xec, 0xef, 0xe7, 0x12, 0x2c, 0xc0, 0x08, 0xe2, 0xf8, 0x7a, 0xfa, 0x85, 0x86, 0xb8,
	0x06, 0x0b, 0x30, 0x09, 0x71, 0x72, 0xb1, 0x7a, 0xf8, 0x87, 0x06, 0x05, 0x0b, 0x30, 0x0b, 0x71,
	0x70, 0xb1, 0xb8, 0x38, 0x46, 0x06, 0x0b, 0xb0, 0x28, 0x79, 0x72, 0x09, 0xc0, 0xdc, 0x59, 0x1c,
	0x9c, 0x9c, 0x98, 0x97, 0x97, 0x5a, 0x24, 0x24, 0x8e, 0xe2, 0x12, 0x6e, 0x23, 0x76, 0xa8, 0x6d,
	0x42, 0x32, 0x5c, 0x9c, 0x70, 0x7f, 0x02, 0x1d, 0xc4, 0x0c, 0x94, 0xe3, 0xd4, 0x83, 0x69, 0x07,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x16, 0x0a, 0xe3, 0x4c, 0x04, 0x01, 0x00, 0x00,
}
